project:
  type: website
  output-dir: docs
  pre-render: copy_public_resume_md_format.r
  post-render: copy_public_resume_pdf_format.r
  #pre-render: knit_resume_to_md.r
  render:
    - "*.qmd"
    - "*.md"
    - "!*xxxx_xx_xx*"
url: https://pdcherry.github.io
website:
  title: "Frameshift"
  navbar:
    right:
      - about.qmd
      - text: CV
        href: Patrick-Cherry-resume.md
      - icon: github
        href: https://github.com/pdcherry
      - icon: mastodon
        href: https://genomic.social/@pcherry
      - icon: instagram
        href: https://pixelfed.social/pcherry
      - icon: linkedin
        href: https://www.linkedin.com/in/p-cherry/
  page-footer: 
    left: Copyright 2024, Patrick Cherry <a rel="me" href="https://fosstodon.org/@pcherry">@pcherry@fosstodon.org</a> or <a rel="me" href="https://genomic.social/@pcherry">@pcherry@genomic.social</a>
  open-graph: true
format:
  html:
    theme:
      light: themes/minty_mod.scss
      dark: themes/cyborg_mod.scss
      #dark: slate
    highlight-style:
      light: themes/gruvbox-light.theme
      dark: themes/gruvbox-dark.theme
    css: styles.css
execute:
  freeze: auto
