project:
  type: website
  output-dir: docs
  pre-render: knit_resume_to_md.r
url: https://pdcherry.github.io
website:
  title: "Frameshift"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/pdcherry
      - icon: mastodon
        href: https://genomic.social/@pcherry
      - icon: instagram
        href: https://pixelfed.social/pcherry
      - icon: linkedin
        href: https://www.linkedin.com/in/p-cherry/
  page-footer: 
    left: Copyright 2023, Patrick Cherry
format:
  html:
    theme: minty
    css: styles.css
execute:
  freeze: auto
