project:
  type: website
  output-dir: docs
  pre-render: knit_resume_to_md.r
  render:
    - "*.qmd"
    - "!*xxxx_xx_xx*"
    - "!*2024_01_03*"
url: https://pdcherry.github.io
website:
  title: "Frameshift"
  navbar:
    right:
      - about.qmd
      - text: CV
        href: Patrick-Cherry-resume.md
      - icon: github
        href: https://github.com/pdcherry
      - icon: mastodon
        href: https://genomic.social/@pcherry
      - icon: instagram
        href: https://pixelfed.social/pcherry
      - icon: linkedin
        href: https://www.linkedin.com/in/p-cherry/
  page-footer: 
    left: Copyright 2023, Patrick Cherry <a rel="me" href="https://genomic.social/@pcherry">@pcherry@genomic.social</a>
format:
  html:
    theme:
      light: minty
      dark: slate
    css: styles.css
execute:
  freeze: auto
