---
#title: "Frameshift Homepage"
#author: "Patrick Cherry"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: true
  filter-ui: true
page-layout: full
#title-block-banner: true
#execute:
#  freeze: true
---
:::{.callout-note}
## I am hiring.
Hi everyone, I am hiring for a Research Associate to join the BillionToOne Research and Development team in Menlo Park to help work on making our Oncology tests more sensitive and broader in scope. I am looking for a BS or MS in Molecular / Cell Biology or related fields with 1-2 years research experience in standard molecular biology techniques, and the ability to quickly learn experimental, mathematical, and statistical concepts. BillionToOne can offer interesting and impactful work, great coworkers, and great benefits. Apply using the link below, or DM me to recommend someone you think would be a good fit.

[Job Post | Research Associate | BillionToOne | Core Development, Oncology](https://grnh.se/0541b3175us)
:::

A blog of indeterminate subject matter and publication frequency from a bioinformatician and data scientist by way of molecular biology.

Likely topics are molecular biology, biological data science, economics, policy, California ballot measure discussion, and outdoor adventures.

```{=html}
<a rel="me" href="https://genomic.social/@pcherry"> </a>
<a rel="me" href="https://fosstodon.org/@pcherry"> </a>
```