<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Patrick Cherry">
<meta name="dcterms.date" content="2024-01-03">

<title>Frameshift - GTEX RNA-seq Liver-specific Process and TF Identification</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Frameshift - GTEX RNA-seq Liver-specific Process and TF Identification">
<meta property="og:description" content="">
<meta property="og:image" content="2024_01_03-liver_creative_commons.jpg">
<meta property="og:site-name" content="Frameshift">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Frameshift</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Patrick-Cherry-resume.html" rel="" target="">
 <span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/pdcherry" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://genomic.social/@pcherry" rel="" target=""><i class="bi bi-mastodon" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://pixelfed.social/pcherry" rel="" target=""><i class="bi bi-instagram" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/p-cherry/" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">GTEX RNA-seq Liver-specific Process and TF Identification</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">code</div>
                <div class="quarto-category">RNAseq</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Patrick Cherry </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">January 3, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#notes-on-approach" id="toc-notes-on-approach" class="nav-link" data-scroll-target="#notes-on-approach">Notes on approach</a></li>
  <li><a href="#patricks-hypothesis" id="toc-patricks-hypothesis" class="nav-link" data-scroll-target="#patricks-hypothesis">Patrick’s hypothesis</a></li>
  </ul></li>
  <li><a href="#metadata-sample-annotations" id="toc-metadata-sample-annotations" class="nav-link" data-scroll-target="#metadata-sample-annotations">Metadata (sample annotations)</a>
  <ul class="collapse">
  <li><a href="#filter-sample-table-to-our-scoped-tissue-types" id="toc-filter-sample-table-to-our-scoped-tissue-types" class="nav-link" data-scroll-target="#filter-sample-table-to-our-scoped-tissue-types">Filter sample table to our scoped tissue types</a></li>
  <li><a href="#import-the-related-bulk-rnaseq-counts" id="toc-import-the-related-bulk-rnaseq-counts" class="nav-link" data-scroll-target="#import-the-related-bulk-rnaseq-counts">Import the related bulk RNAseq counts</a>
  <ul class="collapse">
  <li><a href="#troubleshoot-filtering-samplesmatrix-columns" id="toc-troubleshoot-filtering-samplesmatrix-columns" class="nav-link" data-scroll-target="#troubleshoot-filtering-samplesmatrix-columns">Troubleshoot filtering samples/matrix columns</a></li>
  </ul></li>
  <li><a href="#filter-features-to-protein-coding-genes" id="toc-filter-features-to-protein-coding-genes" class="nav-link" data-scroll-target="#filter-features-to-protein-coding-genes">Filter features to protein-coding genes</a>
  <ul class="collapse">
  <li><a href="#number-of-features" id="toc-number-of-features" class="nav-link" data-scroll-target="#number-of-features">Number of features</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#run-deseq2-analysis" id="toc-run-deseq2-analysis" class="nav-link" data-scroll-target="#run-deseq2-analysis">Run DEseq2 analysis</a>
  <ul class="collapse">
  <li><a href="#prepare-data-object-for-deseq2" id="toc-prepare-data-object-for-deseq2" class="nav-link" data-scroll-target="#prepare-data-object-for-deseq2">Prepare data object for DEseq2</a>
  <ul class="collapse">
  <li><a href="#filter-for-minimum-counts" id="toc-filter-for-minimum-counts" class="nav-link" data-scroll-target="#filter-for-minimum-counts">Filter for minimum counts</a></li>
  </ul></li>
  <li><a href="#run-deseq2-analysis-1" id="toc-run-deseq2-analysis-1" class="nav-link" data-scroll-target="#run-deseq2-analysis-1">Run DEseq2 analysis</a>
  <ul class="collapse">
  <li><a href="#extract-all-contrast-data-from-deseq" id="toc-extract-all-contrast-data-from-deseq" class="nav-link" data-scroll-target="#extract-all-contrast-data-from-deseq">Extract all contrast data from DEseq</a></li>
  </ul></li>
  <li><a href="#prepare-data-with-additional-annotations" id="toc-prepare-data-with-additional-annotations" class="nav-link" data-scroll-target="#prepare-data-with-additional-annotations">Prepare data with additional annotations</a>
  <ul class="collapse">
  <li><a href="#further-explore-the-contrasts" id="toc-further-explore-the-contrasts" class="nav-link" data-scroll-target="#further-explore-the-contrasts">Further explore the contrasts</a></li>
  <li><a href="#ma-plot-analysis-qc" id="toc-ma-plot-analysis-qc" class="nav-link" data-scroll-target="#ma-plot-analysis-qc">MA Plot (analysis QC)</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#cross-contrast-analysis" id="toc-cross-contrast-analysis" class="nav-link" data-scroll-target="#cross-contrast-analysis">Cross-contrast analysis</a>
  <ul class="collapse">
  <li><a href="#summarize-by-feature" id="toc-summarize-by-feature" class="nav-link" data-scroll-target="#summarize-by-feature">Summarize by feature</a></li>
  <li><a href="#pivot-to-wide" id="toc-pivot-to-wide" class="nav-link" data-scroll-target="#pivot-to-wide">Pivot to wide</a></li>
  </ul></li>
  <li><a href="#pathway-gene-ontology-go-enrichment-analysis" id="toc-pathway-gene-ontology-go-enrichment-analysis" class="nav-link" data-scroll-target="#pathway-gene-ontology-go-enrichment-analysis">Pathway / Gene Ontology (GO) Enrichment Analysis</a>
  <ul class="collapse">
  <li><a href="#pathway-analysis" id="toc-pathway-analysis" class="nav-link" data-scroll-target="#pathway-analysis">Pathway analysis</a>
  <ul class="collapse">
  <li><a href="#prepare-gages-needed-data" id="toc-prepare-gages-needed-data" class="nav-link" data-scroll-target="#prepare-gages-needed-data">Prepare GAGE’s needed data</a></li>
  <li><a href="#perpare-deseq2-result-for-gage" id="toc-perpare-deseq2-result-for-gage" class="nav-link" data-scroll-target="#perpare-deseq2-result-for-gage">Perpare DEseq2 result for GAGE</a></li>
  </ul></li>
  <li><a href="#run-gage" id="toc-run-gage" class="nav-link" data-scroll-target="#run-gage">Run GAGE</a>
  <ul class="collapse">
  <li><a href="#view-results" id="toc-view-results" class="nav-link" data-scroll-target="#view-results">View Results</a></li>
  <li><a href="#pathway-plots" id="toc-pathway-plots" class="nav-link" data-scroll-target="#pathway-plots">Pathway plots</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#transcription-factor-enrichment-analysis" id="toc-transcription-factor-enrichment-analysis" class="nav-link" data-scroll-target="#transcription-factor-enrichment-analysis">Transcription Factor Enrichment Analysis</a>
  <ul class="collapse">
  <li><a href="#chip-transcription-factor-data" id="toc-chip-transcription-factor-data" class="nav-link" data-scroll-target="#chip-transcription-factor-data">ChIP Transcription Factor data</a>
  <ul class="collapse">
  <li><a href="#run-gsea-on-tfea.chip" id="toc-run-gsea-on-tfea.chip" class="nav-link" data-scroll-target="#run-gsea-on-tfea.chip">Run GSEA on TFEA.ChIP</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>I use the publicly available bulk RNA-Seq data from <a href="https://www.gtexportal.org/home/downloads/adult-gtex">GTEX</a> (v8) identify biological pathways and processes specific to the liver. I also identify putative transcriptional regulators of these pathways and processes. To ensure that the analysis fits into local memory, I restrict the features in scope to be protein-coding genes, and the tissues in scope to be the following following: heart, kidney, liver, lung, muscle, pancreas, spleen, stomach, pituitary gland, and thyroid.</p>
<section id="notes-on-approach" class="level2">
<h2 class="anchored" data-anchor-id="notes-on-approach">Notes on approach</h2>
<p><a href="https://www.science.org/doi/full/10.1126/science.aaz1776">The GTEx Consortium atlas of genetic regulatory effects across human tissues</a> The Genotype-Tissue Expression (GTEx) project was established to characterize genetic effects on the transcriptome across human tissues and to link these regulatory mechanisms to trait and disease associations.</p>
<p>I’m interpreting “specific to the liver” to mean uniquely expressed in the liver compared to each other tissue in scope. I will express this in the analysis by running instructing DEseq to run a one-to-many test by ranking liver first among the tissue factors, and then running a p-value meta-analysis on the p-value results for features (protein-coding genes) in all comparisons. (Meaning, it only takes one liver-to-tissue comparison revealing that a gene is NOT up-regulated in the liver to remove that gene from consideration.)</p>
</section>
<section id="patricks-hypothesis" class="level2">
<h2 class="anchored" data-anchor-id="patricks-hypothesis">Patrick’s hypothesis</h2>
<p>Given this is liver RNA-seq, I expect to see genes implicated in the liver main roles, namely:</p>
<ul>
<li>conditioning the blood by secreting important proteins into it, like serum albumin, immune complement proteins, C-reactive protein, clotting factors (pre-pro-thrombin, fibrinogen, plasminogen), etc.</li>
<li>cytochrome P450 proteins (CYPxxx), by which the liver catabolizes xenobiotics</li>
<li>glycolysis, gluconeogenesis, and fatty acid catabolism</li>
<li>bile salts catabolism and anabolism (cholesterols, hemoglobin/porphyrin)</li>
<li>amino acid conversion and catabolism</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(usethis)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)                  <span class="co"># for reading and writing csvs</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fs)                     <span class="co"># for filesystem navigation in R</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)                  <span class="co"># for dataframe manipulation</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)                  <span class="co"># for dataframe group nesting and manipulation</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(purrr)                  <span class="co"># for functional programming, including on nested dataframes</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)                 <span class="co"># for reading excel files</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)                <span class="co"># for efficient string manipulation</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)               <span class="co"># for enhanced pipes</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)                  <span class="co"># for model manipulation</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forcats)                <span class="co"># for factor manipulation</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)                <span class="co"># for additional plotting features</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ensembldb)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DESeq2)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AnnotationDbi)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(org.Hs.eg.db)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gage)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pathview)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gageData)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(TFEA.ChIP)              <span class="co"># analyze transcription factor enrichment in a gene set</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(BiocParallel)           <span class="co"># speed up some parallelizeable processing</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="fu">register</span>(<span class="fu">MulticoreParam</span>(<span class="dv">4</span>))     <span class="co"># set core parallelization to 4 CPU cores</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())           <span class="co"># set the default ggplot theme to be clear &amp; cartooney</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="metadata-sample-annotations" class="level1">
<h1>Metadata (sample annotations)</h1>
<p>Samples come from https://github.com/broadinstitute/gtex-v8/blob/master/data/GTEx_Analysis_v8_RNAseq_samples.txt, and have to be manually downloaded.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>gtex_samples <span class="ot">&lt;-</span> <span class="fu">read.delim</span>(<span class="st">"../../GTEx_Analysis_v8_RNAseq_samples.txt"</span>, <span class="at">sep =</span> <span class="st">"</span><span class="sc">\t</span><span class="st">"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"sample_id"</span> <span class="ot">=</span> <span class="fu">str_replace_all</span>(sample_id, <span class="st">"-"</span>, <span class="st">"</span><span class="sc">\\</span><span class="st">."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>gtex_samples <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">count</span>(tissue_id) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                               tissue_id   n
1                        Muscle_Skeletal 803
2                            Whole_Blood 755
3             Skin_Sun_Exposed_Lower_leg 701
4                   Adipose_Subcutaneous 663
5                          Artery_Tibial 663
6                                Thyroid 653
7                           Nerve_Tibial 619
8        Skin_Not_Sun_Exposed_Suprapubic 604
9                                   Lung 578
10                      Esophagus_Mucosa 555
11              Adipose_Visceral_Omentum 541
12                  Esophagus_Muscularis 515
13            Cells_Cultured_fibroblasts 504
14                 Breast_Mammary_Tissue 459
15                          Artery_Aorta 432
16                  Heart_Left_Ventricle 432
17                Heart_Atrial_Appendage 429
18                      Colon_Transverse 406
19   Esophagus_Gastroesophageal_Junction 375
20                         Colon_Sigmoid 373
21                                Testis 361
22                               Stomach 359
23                              Pancreas 328
24                             Pituitary 283
25                         Adrenal_Gland 258
26                          Brain_Cortex 255
27           Brain_Caudate_basal_ganglia 246
28 Brain_Nucleus_accumbens_basal_ganglia 246
29                              Prostate 245
30                      Brain_Cerebellum 241
31                                Spleen 241
32                       Artery_Coronary 240
33                                 Liver 226
34           Brain_Cerebellar_Hemisphere 215
35              Brain_Frontal_Cortex_BA9 209
36           Brain_Putamen_basal_ganglia 205
37                    Brain_Hypothalamus 202
38                     Brain_Hippocampus 197
39        Small_Intestine_Terminal_Ileum 187
40                                 Ovary 180
41  Brain_Anterior_cingulate_cortex_BA24 176
42     Cells_EBV-transformed_lymphocytes 174
43                  Minor_Salivary_Gland 162
44        Brain_Spinal_cord_cervical_c-1 159
45                                Vagina 156
46                        Brain_Amygdala 152
47                                Uterus 142
48                Brain_Substantia_nigra 139
49                         Kidney_Cortex  85
50                               Bladder  21
51                     Cervix_Endocervix  10
52                     Cervix_Ectocervix   9
53                        Fallopian_Tube   9
54                        Kidney_Medulla   4</code></pre>
</div>
</div>
<p>Put <em>liver</em> first in this list, because after filtering, I will use it to set the order of the factors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>tissue_keep <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Liver"</span>, <span class="st">"Heart_Left_Ventricle"</span>, <span class="st">"Heart_Atrial_Appendage"</span>, <span class="st">"Kidney_Cortex"</span>,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Kidney_Medulla"</span>, <span class="st">"Lung"</span>, <span class="st">"Muscle_Skeletal"</span>, <span class="st">"Pancreas"</span>, <span class="st">"Spleen"</span>, <span class="st">"Stomach"</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Pituitary"</span>, <span class="st">"Thyroid"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Double-check I got all the names right</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">all</span>(tissue_keep <span class="sc">%in%</span> gtex_samples[[<span class="st">'tissue_id'</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>Got ’em!</p>
<section id="filter-sample-table-to-our-scoped-tissue-types" class="level2">
<h2 class="anchored" data-anchor-id="filter-sample-table-to-our-scoped-tissue-types">Filter sample table to our scoped tissue types</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>gtex_samples_filtered <span class="ot">&lt;-</span> gtex_samples <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(tissue_id <span class="sc">%in%</span> tissue_keep) <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># on the next line, set order of factors with liver first</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"tissue_id"</span> <span class="ot">=</span> <span class="fu">fct_relevel</span>(<span class="fu">as_factor</span>(tissue_id), tissue_keep) )</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">count</span>(gtex_samples_filtered)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     n
1 4421</code></pre>
</div>
</div>
<p>4421 / 17382 = .254 . We are keeping ~ 25% of samples that were in GTEx v8.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>gtex_samples_filtered <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(tissue_id) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"percent"</span> <span class="ot">=</span> <span class="fu">signif</span>(n <span class="sc">/</span> <span class="fu">sum</span>(n) <span class="sc">*</span> <span class="dv">100</span>, <span class="at">digits =</span> <span class="dv">2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                tissue_id   n percent
1         Muscle_Skeletal 803   18.00
2                 Thyroid 653   15.00
3                    Lung 578   13.00
4    Heart_Left_Ventricle 432    9.80
5  Heart_Atrial_Appendage 429    9.70
6                 Stomach 359    8.10
7                Pancreas 328    7.40
8               Pituitary 283    6.40
9                  Spleen 241    5.50
10                  Liver 226    5.10
11          Kidney_Cortex  85    1.90
12         Kidney_Medulla   4    0.09</code></pre>
</div>
</div>
</section>
<section id="import-the-related-bulk-rnaseq-counts" class="level2">
<h2 class="anchored" data-anchor-id="import-the-related-bulk-rnaseq-counts">Import the related bulk RNAseq counts</h2>
<p>Bulk RNAseq gct files came from: https://www.gtexportal.org/home/downloads/adult-gtex</p>
<p>I’ll use read counts because that’s what DEseq2’s statistical modeling requires. Unzip it first:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> ..</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gunzip</span> <span class="pp">*</span>.gz</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>rna_counts <span class="ot">&lt;-</span> <span class="fu">read.delim</span>(<span class="st">"../../bulk-gex_v8_rna-seq_GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_reads.gct"</span>,</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">sep =</span> <span class="st">"</span><span class="sc">\t</span><span class="st">"</span>, <span class="at">skip =</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  tibble<span class="sc">::</span><span class="fu">column_to_rownames</span>(<span class="at">var =</span> <span class="st">"Name"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="troubleshoot-filtering-samplesmatrix-columns" class="level3">
<h3 class="anchored" data-anchor-id="troubleshoot-filtering-samplesmatrix-columns">Troubleshoot filtering samples/matrix columns</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>rna_counts_cols <span class="ot">&lt;-</span> <span class="fu">colnames</span>(rna_counts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(gtex_samples_filtered[[<span class="st">'sample_id'</span>]] <span class="sc">%in%</span> rna_counts_cols)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4421</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anti_join</span>(gtex_samples_filtered, <span class="fu">as_tibble</span>(rna_counts_cols),</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"sample_id"</span> <span class="ot">=</span> <span class="st">"value"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] sample_id    donor_id     has_genotype tissue_id   
&lt;0 rows&gt; (or 0-length row.names)</code></pre>
</div>
</div>
<p>0 is the desired outcome of an anti-join.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>rna_counts_filtered <span class="ot">&lt;-</span> rna_counts <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(gtex_samples_filtered[[<span class="st">'sample_id'</span>]]) <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.matrix</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(rna_counts_filtered)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 56200  4421</code></pre>
</div>
</div>
<p>Great: filtering went correctly. The dashes-to-periods issue was irksome. We have y = 4421 samples, and 56200 features.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">all</span>(gtex_samples_filtered[[<span class="st">'sample_id'</span>]] <span class="sc">%in%</span> <span class="fu">colnames</span>(rna_counts_filtered))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">all</span>(gtex_samples_filtered[[<span class="st">'sample_id'</span>]] <span class="sc">==</span> <span class="fu">colnames</span>(rna_counts_filtered))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>Great, we are good to continue to DEseq2 DESeqDataSet</p>
</section>
</section>
<section id="filter-features-to-protein-coding-genes" class="level2">
<h2 class="anchored" data-anchor-id="filter-features-to-protein-coding-genes">Filter features to protein-coding genes</h2>
<p>please restrict your analyses to protein-coding genes and the following tissues:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">keytypes</span>(org.Hs.eg.db)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "ACCNUM"       "ALIAS"        "ENSEMBL"      "ENSEMBLPROT"  "ENSEMBLTRANS"
 [6] "ENTREZID"     "ENZYME"       "EVIDENCE"     "EVIDENCEALL"  "GENENAME"    
[11] "GENETYPE"     "GO"           "GOALL"        "IPI"          "MAP"         
[16] "OMIM"         "ONTOLOGY"     "ONTOLOGYALL"  "PATH"         "PFAM"        
[21] "PMID"         "PROSITE"      "REFSEQ"       "SYMBOL"       "UCSCKG"      
[26] "UNIPROT"     </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>ensgs_to_filter <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="st">"ENSG"</span> <span class="ot">=</span> <span class="fu">dimnames</span>(rna_counts_filtered)[[<span class="dv">1</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>ensgs_filtered_protein <span class="ot">&lt;-</span> ensgs_to_filter <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"short_ensg"</span> <span class="ot">=</span> <span class="fu">str_remove</span>(ENSG, <span class="st">"(?&lt;=ENSG</span><span class="sc">\\</span><span class="st">d{1,14})</span><span class="sc">\\</span><span class="st">.{0,1}</span><span class="sc">\\</span><span class="st">d{0,3}$"</span>),</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>         <span class="st">"genetype"</span> <span class="ot">=</span> <span class="fu">mapIds</span>(org.Hs.eg.db,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                           <span class="at">keys =</span> short_ensg,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                           <span class="at">column =</span> <span class="st">"GENETYPE"</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>                           <span class="at">keytype =</span> <span class="st">"ENSEMBL"</span>,</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>                           <span class="at">multiVals =</span> <span class="st">"first"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>'select()' returned 1:many mapping between keys and columns</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">count</span>(ensgs_filtered_protein, genetype) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   genetype           n
   &lt;chr&gt;          &lt;int&gt;
 1 &lt;NA&gt;           21144
 2 protein-coding 19198
 3 pseudo          8918
 4 ncRNA           5820
 5 snoRNA           654
 6 other            368
 7 snRNA             75
 8 rRNA              20
 9 scRNA              2
10 unknown            1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>ensgs_filtered_protein <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(ensgs_filtered_protein, genetype <span class="sc">==</span> <span class="st">"protein-coding"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Actually apply the filter below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>rna_counts_filtered <span class="ot">&lt;-</span> rna_counts_filtered[ensgs_filtered_protein[[<span class="dv">1</span>]], ]</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(rna_counts_filtered)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 19198  4421</code></pre>
</div>
</div>
<section id="number-of-features" class="level3">
<h3 class="anchored" data-anchor-id="number-of-features">Number of features</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">count</span>(ensgs_to_filter)[[<span class="dv">1</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 56200</code></pre>
</div>
</div>
<p>19184/56200 = 34%, so we are keeping 34% of features in the counts matrix, because ENSEMBL annotates them as protein-coding. Thus we are jettisoning 66% of features as being non-protein coding. What the ENCODE db indicates is that annotated ENCODE entries are the most common, followed by pseudo, ncRNA, snoRNA, “other,” snRNA, rRNA, scRNA, and “unknown.”</p>
</section>
</section>
</section>
<section id="run-deseq2-analysis" class="level1">
<h1>Run DEseq2 analysis</h1>
<section id="prepare-data-object-for-deseq2" class="level2">
<h2 class="anchored" data-anchor-id="prepare-data-object-for-deseq2">Prepare data object for DEseq2</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>tissue_DE <span class="ot">&lt;-</span> <span class="fu">DESeqDataSetFromMatrix</span>(<span class="at">countData =</span> rna_counts_filtered,</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">colData =</span> gtex_samples_filtered,</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">design =</span> <span class="sc">~</span> tissue_id)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>tissue_DE</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class: DESeqDataSet 
dim: 19198 4421 
metadata(1): version
assays(1): counts
rownames(19198): ENSG00000186092.4 ENSG00000187634.11 ...
  ENSG00000198695.2 ENSG00000198727.2
rowData names(0):
colnames(4421): GTEX.1117F.0426.SM.5EGHI GTEX.1117F.0726.SM.5GIEN ...
  GTEX.ZZPU.1426.SM.5GZZ6 GTEX.ZZPU.2626.SM.5E45Y
colData names(4): sample_id donor_id has_genotype tissue_id</code></pre>
</div>
</div>
<section id="filter-for-minimum-counts" class="level3">
<h3 class="anchored" data-anchor-id="filter-for-minimum-counts">Filter for minimum counts</h3>
<p>Filter for features (genes) where there are less than 113 or more samples with normalized counts greater than or equal to 5. (113 is half the number of liver samples in the data, allowing for at least some dispersion in at least among the samples of the tissue type we want to understand.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>tissue_DE <span class="ot">&lt;-</span> <span class="fu">estimateSizeFactors</span>(tissue_DE)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>idx <span class="ot">&lt;-</span> <span class="fu">rowSums</span>( <span class="fu">counts</span>(tissue_DE, <span class="at">normalized =</span> <span class="cn">TRUE</span>) <span class="sc">&gt;=</span> <span class="dv">5</span> ) <span class="sc">&gt;=</span> <span class="dv">113</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>tissue_DE <span class="ot">&lt;-</span> tissue_DE[idx,]</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(tissue_DE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18023  4421</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">56200-33387</span>);</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 22813</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">56200-33387</span>)<span class="sc">/</span><span class="dv">56200</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4059253</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">19184-18013</span>)<span class="sc">/</span><span class="dv">19184</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.06104045</code></pre>
</div>
</div>
<p>Originally, when filtering for features with a minimum number of counts over the minimum number of genes, I filtered out 22,813 (40.6%) based on low counts / coverage. <em>However, now the I’m filtering genes for counts <em>after</em> filtering for protein coding genes</em>, only 6.1% of features are dropped. This difference in proportionality indicates that low count features and protein coding genes are not necessarily independent. In fact, the non-protein-coding features were enriched for low expression levels across many of the samples.</p>
</section>
</section>
<section id="run-deseq2-analysis-1" class="level2">
<h2 class="anchored" data-anchor-id="run-deseq2-analysis-1">Run DEseq2 analysis</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(gtex_samples, gtex_samples_filtered, rna_counts_filtered, rna_counts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>tissue_DE <span class="ot">&lt;-</span> <span class="fu">DESeq</span>(tissue_DE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>using pre-existing size factors</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>estimating dispersions</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>gene-wise dispersion estimates</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>mean-dispersion relationship</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>final dispersion estimates</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>fitting model and testing</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>-- replacing outliers and refitting for 237 genes
-- DESeq argument 'minReplicatesForReplace' = 7 
-- original counts are preserved in counts(dds)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>estimating dispersions</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>fitting model and testing</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>contrasts_no_intercept <span class="ot">&lt;-</span> <span class="fu">resultsNames</span>(tissue_DE)[<span class="dv">2</span><span class="sc">:</span><span class="fu">length</span>(<span class="fu">resultsNames</span>(tissue_DE))]</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>contrasts_no_intercept</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "tissue_id_Heart_Left_Ventricle_vs_Liver"  
 [2] "tissue_id_Heart_Atrial_Appendage_vs_Liver"
 [3] "tissue_id_Kidney_Cortex_vs_Liver"         
 [4] "tissue_id_Kidney_Medulla_vs_Liver"        
 [5] "tissue_id_Lung_vs_Liver"                  
 [6] "tissue_id_Muscle_Skeletal_vs_Liver"       
 [7] "tissue_id_Pancreas_vs_Liver"              
 [8] "tissue_id_Spleen_vs_Liver"                
 [9] "tissue_id_Stomach_vs_Liver"               
[10] "tissue_id_Pituitary_vs_Liver"             
[11] "tissue_id_Thyroid_vs_Liver"               </code></pre>
</div>
</div>
<section id="extract-all-contrast-data-from-deseq" class="level3">
<h3 class="anchored" data-anchor-id="extract-all-contrast-data-from-deseq">Extract all contrast data from DEseq</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>combine_contrast_results <span class="ot">&lt;-</span> <span class="cf">function</span>(deseq_obj){</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  contrasts_no_intercept <span class="ot">&lt;-</span> <span class="fu">resultsNames</span>(deseq_obj)[<span class="dv">2</span><span class="sc">:</span><span class="fu">length</span>(<span class="fu">resultsNames</span>(deseq_obj))]</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(purrr<span class="sc">::</span><span class="fu">map</span>(contrasts_no_intercept, <span class="sc">~</span> <span class="fu">mutate</span>(</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>    tibble<span class="sc">::</span><span class="fu">rownames_to_column</span>(<span class="fu">as.data.frame</span>(<span class="fu">results</span>(deseq_obj, <span class="at">name =</span> .x)),</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"ENSG"</span>),</span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"contrast"</span> <span class="ot">=</span> .x)</span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>tissue_DE_results_long <span class="ot">&lt;-</span> <span class="fu">combine_contrast_results</span>(tissue_DE) <span class="sc">%&gt;%</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"contrast"</span> <span class="ot">=</span> <span class="fu">str_remove</span>(contrast, <span class="st">"^tissue_id_"</span>))</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">count</span>(tissue_DE_results_long, contrast)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          contrast     n
1  Heart_Atrial_Appendage_vs_Liver 18023
2    Heart_Left_Ventricle_vs_Liver 18023
3           Kidney_Cortex_vs_Liver 18023
4          Kidney_Medulla_vs_Liver 18023
5                    Lung_vs_Liver 18023
6         Muscle_Skeletal_vs_Liver 18023
7                Pancreas_vs_Liver 18023
8               Pituitary_vs_Liver 18023
9                  Spleen_vs_Liver 18023
10                Stomach_vs_Liver 18023
11                Thyroid_vs_Liver 18023</code></pre>
</div>
</div>
</section>
</section>
<section id="prepare-data-with-additional-annotations" class="level2">
<h2 class="anchored" data-anchor-id="prepare-data-with-additional-annotations">Prepare data with additional annotations</h2>
<section id="check-if-ensg-string-manipulation-prodcuces-unique-values" class="level4">
<h4 class="anchored" data-anchor-id="check-if-ensg-string-manipulation-prodcuces-unique-values">Check if ENSG string manipulation prodcuces unique values</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">count</span>(<span class="fu">as_tibble</span>(<span class="fu">str_remove</span>(<span class="fu">row.names</span>(tissue_DE_results_long),</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>           <span class="st">"(?&lt;=ENSG</span><span class="sc">\\</span><span class="st">d{1,14})</span><span class="sc">\\</span><span class="st">.{0,1}</span><span class="sc">\\</span><span class="st">d{0,3}$"</span>)), value) <span class="sc">%&gt;%</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(n);</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
      n     nn
  &lt;int&gt;  &lt;int&gt;
1     1 198253</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">count</span>(<span class="fu">as_tibble</span>(<span class="fu">row.names</span>(tissue_DE_results_long)), value) <span class="sc">%&gt;%</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
      n     nn
  &lt;int&gt;  &lt;int&gt;
1     1 198253</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>tissue_DE_results_long <span class="ot">&lt;-</span> tissue_DE_results_long <span class="sc">%&gt;%</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"short_ensg"</span> <span class="ot">=</span> <span class="fu">str_remove</span>(ENSG, <span class="st">"(?&lt;=ENSG</span><span class="sc">\\</span><span class="st">d{1,14})</span><span class="sc">\\</span><span class="st">.{0,1}</span><span class="sc">\\</span><span class="st">d{0,3}$"</span>),</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>         <span class="st">"symbol"</span> <span class="ot">=</span> <span class="fu">mapIds</span>(org.Hs.eg.db,</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>                           <span class="at">keys =</span> short_ensg,</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>                           <span class="at">column =</span> <span class="st">"SYMBOL"</span>,</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>                           <span class="at">keytype =</span> <span class="st">"ENSEMBL"</span>,</span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>                           <span class="at">multiVals =</span> <span class="st">"first"</span>),</span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>         <span class="st">"entrez"</span> <span class="ot">=</span> <span class="fu">mapIds</span>(org.Hs.eg.db,</span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a>                           <span class="at">keys =</span> short_ensg,</span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a>                           <span class="at">column =</span> <span class="st">"ENTREZID"</span>,</span>
<span id="cb69-11"><a href="#cb69-11" aria-hidden="true" tabindex="-1"></a>                           <span class="at">keytype =</span> <span class="st">"ENSEMBL"</span>,</span>
<span id="cb69-12"><a href="#cb69-12" aria-hidden="true" tabindex="-1"></a>                           <span class="at">multiVals =</span> <span class="st">"first"</span>),</span>
<span id="cb69-13"><a href="#cb69-13" aria-hidden="true" tabindex="-1"></a>         <span class="st">"name"</span> <span class="ot">=</span> <span class="fu">mapIds</span>(org.Hs.eg.db,</span>
<span id="cb69-14"><a href="#cb69-14" aria-hidden="true" tabindex="-1"></a>                         <span class="at">keys =</span> short_ensg,</span>
<span id="cb69-15"><a href="#cb69-15" aria-hidden="true" tabindex="-1"></a>                         <span class="at">column =</span> <span class="st">"GENENAME"</span>,</span>
<span id="cb69-16"><a href="#cb69-16" aria-hidden="true" tabindex="-1"></a>                         <span class="at">keytype =</span> <span class="st">"ENSEMBL"</span>,</span>
<span id="cb69-17"><a href="#cb69-17" aria-hidden="true" tabindex="-1"></a>                         <span class="at">multiVals =</span> <span class="st">"first"</span>)</span>
<span id="cb69-18"><a href="#cb69-18" aria-hidden="true" tabindex="-1"></a>         )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>'select()' returned 1:many mapping between keys and columns
'select()' returned 1:many mapping between keys and columns
'select()' returned 1:many mapping between keys and columns</code></pre>
</div>
</div>
</section>
<section id="further-explore-the-contrasts" class="level3">
<h3 class="anchored" data-anchor-id="further-explore-the-contrasts">Further explore the contrasts</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>top_10_hits_summary <span class="ot">&lt;-</span> tissue_DE_results_long <span class="sc">%&gt;%</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"log2FoldChange"</span> <span class="ot">=</span> <span class="sc">-</span><span class="dv">1</span><span class="sc">*</span>log2FoldChange) <span class="sc">%&gt;%</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(contrast) <span class="sc">%&gt;%</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(stat, log2FoldChange) <span class="sc">%&gt;%</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(<span class="st">"contrast"</span>, <span class="st">"short_ensg"</span>, <span class="st">"symbol"</span>, <span class="st">"entrez"</span>, <span class="st">"name"</span>, <span class="st">"log2FoldChange"</span>)</span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>top_10_hits_summary <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="st">"contrast"</span>, <span class="st">"symbol"</span>, <span class="st">"name"</span>, <span class="st">"log2FoldChange"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 110 × 4
# Groups:   contrast [11]
   contrast                        symbol  name                   log2FoldChange
   &lt;chr&gt;                           &lt;chr&gt;   &lt;chr&gt;                           &lt;dbl&gt;
 1 Heart_Atrial_Appendage_vs_Liver SLC27A5 solute carrier family…           7.77
 2 Heart_Atrial_Appendage_vs_Liver RDH16   retinol dehydrogenase…           9.76
 3 Heart_Atrial_Appendage_vs_Liver SLC22A1 solute carrier family…          11.8 
 4 Heart_Atrial_Appendage_vs_Liver CYP2E1  cytochrome P450 famil…          11.5 
 5 Heart_Atrial_Appendage_vs_Liver ASGR1   asialoglycoprotein re…          10.1 
 6 Heart_Atrial_Appendage_vs_Liver CYP2D6  cytochrome P450 famil…           8.74
 7 Heart_Atrial_Appendage_vs_Liver CPS1    carbamoyl-phosphate s…           8.98
 8 Heart_Atrial_Appendage_vs_Liver APOM    apolipoprotein M                 7.20
 9 Heart_Atrial_Appendage_vs_Liver ATF5    activating transcript…           7.22
10 Heart_Atrial_Appendage_vs_Liver MST1    macrophage stimulatin…           7.25
# ℹ 100 more rows</code></pre>
</div>
</div>
<p>This is looking promising. When sorted by statistic and the top ten genes are displayed from each tissue, there are many common genes that are relatively up-regulated (in mRNA expression) in liver compared to each of the other tissues. SLC27A5 is very commonly (and very strongly) up-regulated in liver; RDH16 and CPS1 are as well.</p>
</section>
<section id="ma-plot-analysis-qc" class="level3">
<h3 class="anchored" data-anchor-id="ma-plot-analysis-qc">MA Plot (analysis QC)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>ma_plot <span class="ot">&lt;-</span> tissue_DE_results_long <span class="sc">%&gt;%</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> log2FoldChange, <span class="at">x =</span> baseMean)) <span class="sc">+</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.1</span>, <span class="at">size =</span> .<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density_2d</span>() <span class="sc">+</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">method =</span> lm, <span class="at">color =</span> <span class="st">"yellow"</span>, <span class="at">linewidth =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"MA-plot: a scatter plot of log2 fold changes"</span>,</span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"mean of normalized counts"</span>,</span>
<span id="cb73-9"><a href="#cb73-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"log2 fold change"</span>) <span class="sc">+</span></span>
<span id="cb73-10"><a href="#cb73-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> contrast)</span>
<span id="cb73-11"><a href="#cb73-11" aria-hidden="true" tabindex="-1"></a>ma_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="2024_01_03-GTEX_RNA_seq_liver_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>For all contrasts, the data points (gene IDs) are roughly symmetric around the x-axis (indicating no systematic bias), and the majority are close to the x-axis, indicating many genes are not differentially expressed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>ma_hist <span class="ot">&lt;-</span> tissue_DE_results_long <span class="sc">%&gt;%</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(log2FoldChange)) <span class="sc">+</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"MA-plot: histogram of log2 fold changes"</span>,</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"number of genes"</span>,</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"log2 fold change"</span>) <span class="sc">+</span></span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> contrast)</span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>ma_hist</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="2024_01_03-GTEX_RNA_seq_liver_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>ma_hist_stats <span class="ot">&lt;-</span> tissue_DE_results_long <span class="sc">%&gt;%</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(contrast) <span class="sc">%&gt;%</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="st">"mean log2FoldChange"</span> <span class="ot">=</span> <span class="fu">mean</span>(log2FoldChange),</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"S.D. log2FoldChange"</span> <span class="ot">=</span> <span class="fu">sd</span>(log2FoldChange),</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"n features"</span> <span class="ot">=</span> <span class="fu">n</span>())</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>ma_hist_stats</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 4
   contrast             `mean log2FoldChange` `S.D. log2FoldChange` `n features`
   &lt;chr&gt;                                &lt;dbl&gt;                 &lt;dbl&gt;        &lt;int&gt;
 1 Heart_Atrial_Append…               -0.0807                  2.49        18023
 2 Heart_Left_Ventricl…               -0.160                   2.53        18023
 3 Kidney_Cortex_vs_Li…                0.120                   2.10        18023
 4 Kidney_Medulla_vs_L…               -0.0501                  2.29        18023
 5 Lung_vs_Liver                       0.134                   2.37        18023
 6 Muscle_Skeletal_vs_…               -0.342                   2.77        18023
 7 Pancreas_vs_Liver                  -0.0455                  2.21        18023
 8 Pituitary_vs_Liver                  0.229                   2.69        18023
 9 Spleen_vs_Liver                    -0.156                   2.36        18023
10 Stomach_vs_Liver                    0.112                   2.27        18023
11 Thyroid_vs_Liver                   -0.0922                  2.37        18023</code></pre>
</div>
</div>
<p>As a clearer summary plot, the histograms for each contrast a preponderance of genes are close to the 0 on the x-axis, indicating many features have limited fold change between samples.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>stat_hist <span class="ot">&lt;-</span> tissue_DE_results_long <span class="sc">%&gt;%</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(stat)) <span class="sc">+</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">40</span>) <span class="sc">+</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Stat (statistic)"</span>,</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"number of genes"</span>,</span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Statistic"</span>) <span class="sc">+</span></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> contrast)</span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>stat_hist</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="2024_01_03-GTEX_RNA_seq_liver_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>While the test statistic outputted by DEseq2 is less “clipped” to zero than the p-values (many of which exhaust the range and get reported as 0.000000e+00), the statistic range/distribution is not the same for all contrasts, notably for the Kidney Medulla vs Liver comparison. This can be explained from the <a href="#Filter-sample-table-to-our-scoped-tissue-types">Filter sample table to our scoped tissue types</a> section of this document, which shows the Kidney Medulla GTEx tissue set as having far fewer samples (n = 4) than the other tissue types (mean = 368, sd = 230).</p>
<p>As long as we <code>group_by()</code> when ranking, sorting, and otherwise comparing (in long format), this should be okay. Once pivoted into wide format, this can present a problem because not every column of values will be able to react similarly to the same ranking, sorting, or cut-offs.</p>
</section>
</section>
</section>
<section id="cross-contrast-analysis" class="level1">
<h1>Cross-contrast analysis</h1>
<section id="summarize-by-feature" class="level2">
<h2 class="anchored" data-anchor-id="summarize-by-feature">Summarize by feature</h2>
<p>Which is effectively a wide format, appropriate for joining. (Grouped-by calculations in the same column run more efficiently and are easier to program than row-wise multi-column calculations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>tissue_DE_results_feature_summary <span class="ot">&lt;-</span> tissue_DE_results_long <span class="sc">%&gt;%</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">c</span>(<span class="st">"log2FoldChange"</span>, <span class="st">"stat"</span>),</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">.fns =</span> <span class="fu">c</span>(<span class="st">"mean"</span> <span class="ot">=</span> mean, <span class="st">"sd"</span> <span class="ot">=</span> sd,</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>                            <span class="st">"below_zero_min"</span> <span class="ot">=</span> <span class="er">~</span> <span class="fu">min</span>( (.x[.x <span class="sc">&lt;</span><span class="dv">0</span>]) ) ),</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">.names =</span> <span class="st">"{.fn}_{.col}"</span>),</span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">c</span>(<span class="st">"lfcSE"</span>, <span class="st">"pvalue"</span>, <span class="st">"padj"</span>),</span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">.fns =</span> <span class="fu">c</span>(<span class="st">"mean"</span> <span class="ot">=</span> mean, <span class="st">"sd"</span> <span class="ot">=</span> sd,</span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a>                            <span class="st">"min"</span> <span class="ot">=</span> min),</span>
<span id="cb78-9"><a href="#cb78-9" aria-hidden="true" tabindex="-1"></a>                   <span class="at">.names =</span> <span class="st">"{.fn}_{.col}"</span>),</span>
<span id="cb78-10"><a href="#cb78-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">.by =</span> <span class="fu">c</span>(<span class="st">"ENSG"</span>, <span class="st">"short_ensg"</span>, <span class="st">"symbol"</span>, <span class="st">"entrez"</span>, <span class="st">"name"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There were 4798 warnings in `summarize()`.
The first warning was:
ℹ In argument: `across(...)`.
ℹ In group 7: `ENSG = "ENSG00000188290.10"`, `short_ensg = "ENSG00000188290"`,
  `symbol = "HES4"`, `entrez = "57801"`, `name = "hes family bHLH transcription
  factor 4"`.
Caused by warning in `min()`:
! no non-missing arguments to min; returning Inf
ℹ Run `dplyr::last_dplyr_warnings()` to see the 4797 remaining warnings.</code></pre>
</div>
</div>
<p>To explain why I’m contriving these summary statistics, I have to first acknowledge that downstream processing (GO analysis, TF.ChIP) expects continuous data ( <em>e.g.</em> <code>log2FoldChange</code>, <code>adj.p.val</code>) for <em>both</em> the up-regulated and down-regulated features. Thus, in drawing conclusions from the comparisons, I am balancing maintaining continuous variables that can be used later with summary statistics that <em>suggest</em> consistency across all the tissue type comparisons made (and in the case of the highly confident features/genes, these suggestive consistency metrics indicate high levels of agreement).</p>
<p>These metrics are the <code>mean_log2FoldChange</code>, <code>sd_log2FoldChange</code>, and the <code>below_zero_min_log2FoldChange</code>, (as well as these versions on <code>stat</code> and <code>padj</code>). Together, these continuous feature summary metrics describe how consistently the metrics are across comparisons (e.g.&nbsp;liver to thyroid, liver to lung, etc.). When a feature is specific to the liver, the mean will be negative and large, the sd will be smaller than the mean, and the min_below_zero will not be far away from the mean. Such an outcome indicates that all the comparisons agree that a gene is specifically up-regulated in the liver compared to all other tissues considered here.</p>
<p>Applying these summary transformations to the <code>log2FoldChange</code>, <code>pvalue</code>, and <code>padj</code> are reasonable because these metrics either do not depend on the number of samples (<code>log2FoldChange</code>), or account for the number of samples in the condition (<code>pvalue</code>, and <code>padj</code>), explicitly allowing for comparisons between conditions.</p>
</section>
<section id="pivot-to-wide" class="level2">
<h2 class="anchored" data-anchor-id="pivot-to-wide">Pivot to wide</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>tissue_DE_results_wide <span class="ot">&lt;-</span> tissue_DE_results_long <span class="sc">%&gt;%</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">id_cols =</span> <span class="fu">c</span>(<span class="st">"ENSG"</span>, <span class="st">"short_ensg"</span>, <span class="st">"symbol"</span>, <span class="st">"entrez"</span>, <span class="st">"name"</span>),</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">names_from =</span> <span class="st">"contrast"</span>,</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> <span class="fu">c</span>(<span class="st">"baseMean"</span>, <span class="st">"log2FoldChange"</span>, <span class="st">"lfcSE"</span>, <span class="st">"stat"</span>, <span class="st">"pvalue"</span>, <span class="st">"padj"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(tissue_DE_results_feature_summary,</span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"ENSG"</span>, <span class="st">"short_ensg"</span>, <span class="st">"symbol"</span>, <span class="st">"entrez"</span>, <span class="st">"name"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(short_ensg, mean_log2FoldChange, mean_stat, symbol, name,</span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>           sd_log2FoldChange, below_zero_min_log2FoldChange, sd_stat, below_zero_min_stat, mean_lfcSE,</span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a>           sd_lfcSE, min_lfcSE, mean_pvalue, sd_pvalue, min_pvalue, mean_padj, sd_padj, min_padj) <span class="sc">%&gt;%</span></span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(mean_padj, mean_log2FoldChange)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="pathway-gene-ontology-go-enrichment-analysis" class="level1">
<h1>Pathway / Gene Ontology (GO) Enrichment Analysis</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">slice_head</span>(dplyr<span class="sc">::</span><span class="fu">select</span>(tissue_DE_results_wide,</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>                         mean_log2FoldChange, sd_log2FoldChange, mean_pvalue, symbol, name),</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">n =</span> <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 5
   mean_log2FoldChange sd_log2FoldChange mean_pvalue symbol  name               
                 &lt;dbl&gt;             &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;              
 1               -7.60             0.560   1.66e-214 SLC27A5 solute carrier fam…
 2               -9.37             0.785   5.51e-156 RDH16   retinol dehydrogen…
 3               -9.48             0.401   5.40e-152 CPS1    carbamoyl-phosphat…
 4               -8.15             1.04    1.47e-147 A1BG    alpha-1-B glycopro…
 5               -9.56             1.28    1.90e-135 ASGR1   asialoglycoprotein…
 6              -10.5              0.842   1.91e-124 CYP2E1  cytochrome P450 fa…
 7              -10.5              1.93    7.35e-119 VTN     vitronectin        
 8              -10.3              0.948   7.10e-118 SLC22A1 solute carrier fam…
 9               -6.96             0.329   1.60e-116 ATF5    activating transcr…
10               -6.88             1.01    2.56e-106 ANG     angiogenin         
11              -11.3              2.46    7.90e-100 APOB    apolipoprotein B   
12              -11.5              1.01    5.25e- 98 HPX     hemopexin          
13               -7.68             1.31    2.42e- 97 ITIH4   inter-alpha-trypsi…
14              -12.0              1.89    2.99e- 92 APOA1   apolipoprotein A1  
15              -10.3              1.84    1.37e- 90 TFR2    transferrin recept…
16               -4.45             0.542   1.93e- 88 DHODH   dihydroorotate deh…
17               -9.34             1.81    6.04e- 88 APOC1   apolipoprotein C1  
18              -10.7              1.03    3.93e- 86 TF      transferrin        
19               -7.63             1.10    5.78e- 85 CYP2D6  cytochrome P450 fa…
20                4.33             2.05    6.70e- 84 AIF1L   allograft inflamma…</code></pre>
</div>
</div>
<p>Checking in on genes and hypotheses:</p>
<ol type="1">
<li>conditioning the blood by secreting important proteins into it, like serum albumin, immune complement proteins, C-reactive protein, clotting factors (pre-pro-thrombin, fibrinogen, plasminogen), etc.
<ul>
<li>fibrinogen alpha chain</li>
<li>amyloid P component, serum</li>
<li>coagulation factor IX</li>
<li>fibrinogen beta chain</li>
<li>complement C8 beta chain</li>
<li>plasminogen</li>
<li>fibrinogen gamma chain</li>
<li>C-reactive protein</li>
<li>complement factor H related 2</li>
<li>complement factor H related 5</li>
<li>complement C8 alpha chain</li>
<li>coagulation factor II, thrombin</li>
<li>albumin</li>
<li>complement C9</li>
<li>coagulation factor XIII B chain</li>
</ul></li>
<li>cytochrome P450 proteins (CYPxxx), by which the liver catabolizes xenobiotics
<ul>
<li>cytochrome P450 family 2 subfamily B member 6</li>
<li>cytochrome P450 family 2 subfamily C member 9</li>
<li>cytochrome P450 family 4 subfamily F member 2</li>
</ul></li>
<li>glycolysis, gluconeogenesis, and fatty acid catabolism
<ul>
<li>apolipoprotein C3</li>
<li>apolipoprotein H</li>
<li>apolipoprotein A2</li>
<li>glucose-6-phosphatase catalytic subunit 1</li>
<li>aldolase, fructose-bisphosphate B</li>
</ul></li>
<li>bile salts catabolism and anabolism (cholesterols, hemoglobin/porphyrin)
<ul>
<li>??? (we’ll see later in the pathways analysis)</li>
</ul></li>
<li>amino acid conversion and catabolism
<ul>
<li>alanine–glyoxylate aminotransferase</li>
<li>tyrosine aminotransferase</li>
<li>alanine–glyoxylate aminotransferase 2</li>
</ul></li>
</ol>
<p>I didn’t find many bile salts and cholesterol metabolism genes. Curious. Maybe this is a lesser function of the liver than I imagined, or maybe tissue sampling area makes a difference.</p>
<p>I also recovered some interesting “other” proteins:</p>
<ul>
<li>GC vitamin D binding protein</li>
<li>serpin family A member 7</li>
<li>hydroxyacid oxidase 1</li>
<li>UDP glucuronosyltransferase family 2 member B10</li>
<li>kininogen 1</li>
<li>mannose binding lectin 2</li>
<li>UDP glucuronosyltransferase family 2 member B4</li>
<li>serpin family A member 11</li>
<li>secreted phosphoprotein 2</li>
<li>solute carrier family 2 member 2</li>
<li>carboxypeptidase N subunit 1</li>
<li>cAMP responsive element binding protein 3 like 3</li>
<li>insulin like growth factor binding protein 1</li>
</ul>
<p>Themes on vitamin D, UDP-yl-ation (a means of preparing xenobiotics for excretion), and regulatory / signaling proteins.</p>
<section id="pathway-analysis" class="level2">
<h2 class="anchored" data-anchor-id="pathway-analysis">Pathway analysis</h2>
<p>with GAGE</p>
<section id="prepare-gages-needed-data" class="level3">
<h3 class="anchored" data-anchor-id="prepare-gages-needed-data">Prepare GAGE’s needed data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(kegg.sets.hs)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(sigmet.idx.hs)</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>kegg.sets.hs <span class="ot">=</span> kegg.sets.hs[sigmet.idx.hs]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="perpare-deseq2-result-for-gage" class="level3">
<h3 class="anchored" data-anchor-id="perpare-deseq2-result-for-gage">Perpare DEseq2 result for GAGE</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>foldchanges <span class="ot">=</span> tissue_DE_results_wide<span class="sc">$</span>mean_log2FoldChange</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(foldchanges) <span class="ot">=</span> tissue_DE_results_wide<span class="sc">$</span>entrez</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(foldchanges)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     10998       8608       1373          1        432       1571 
 -7.601432  -9.367489  -9.478086  -8.152599  -9.564476 -10.454284 </code></pre>
</div>
</div>
</section>
</section>
<section id="run-gage" class="level2">
<h2 class="anchored" data-anchor-id="run-gage">Run GAGE</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>keggres <span class="ot">=</span> <span class="fu">gage</span>(foldchanges, <span class="at">gsets =</span> kegg.sets.hs, <span class="at">same.dir =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="view-results" class="level3">
<h3 class="anchored" data-anchor-id="view-results">View Results</h3>
<p>Remember that “down-regulated” (i.e.&nbsp;the “$less” table) is <em>up-regulated</em> in liver, due to the DEseq contrasts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.data.frame</span>(<span class="fu">head</span>(keggres<span class="sc">$</span>less, <span class="dv">20</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="st">"p.geomean"</span>, <span class="st">"stat.mean"</span>, <span class="st">"p.val"</span>, <span class="st">"set.size"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                         p.geomean stat.mean
hsa00830 Retinol metabolism                           2.779302e-15 -9.570937
hsa00982 Drug metabolism - cytochrome P450            1.480851e-13 -8.552116
hsa00980 Metabolism of xenobiotics by cytochrome P450 3.742583e-12 -7.909573
hsa00140 Steroid hormone biosynthesis                 7.829862e-12 -7.983659
hsa00983 Drug metabolism - other enzymes              3.227821e-11 -7.785412
hsa04610 Complement and coagulation cascades          1.590346e-10 -7.112879
hsa00260 Glycine, serine and threonine metabolism     8.543084e-08 -6.071404
hsa00053 Ascorbate and aldarate metabolism            3.398045e-07 -6.247136
hsa04146 Peroxisome                                   3.456134e-07 -5.215038
hsa00071 Fatty acid metabolism                        8.363970e-07 -5.220379
hsa00040 Pentose and glucuronate interconversions     8.446235e-07 -5.659101
hsa00860 Porphyrin and chlorophyll metabolism         3.474540e-06 -4.994513
hsa00500 Starch and sucrose metabolism                5.047958e-06 -4.774060
hsa00380 Tryptophan metabolism                        1.180799e-05 -4.535570
hsa00280 Valine, leucine and isoleucine degradation   2.437705e-05 -4.277734
hsa03320 PPAR signaling pathway                       4.831137e-05 -4.070571
hsa04976 Bile secretion                               5.608401e-05 -4.037952
hsa04975 Fat digestion and absorption                 8.538313e-05 -4.013194
hsa00120 Primary bile acid biosynthesis               1.087369e-04 -4.465205
hsa00591 Linoleic acid metabolism                     1.465698e-04 -4.016737
                                                             p.val set.size
hsa00830 Retinol metabolism                           2.779302e-15       60
hsa00982 Drug metabolism - cytochrome P450            1.480851e-13       68
hsa00980 Metabolism of xenobiotics by cytochrome P450 3.742583e-12       66
hsa00140 Steroid hormone biosynthesis                 7.829862e-12       52
hsa00983 Drug metabolism - other enzymes              3.227821e-11       48
hsa04610 Complement and coagulation cascades          1.590346e-10       69
hsa00260 Glycine, serine and threonine metabolism     8.543084e-08       32
hsa00053 Ascorbate and aldarate metabolism            3.398045e-07       22
hsa04146 Peroxisome                                   3.456134e-07       78
hsa00071 Fatty acid metabolism                        8.363970e-07       43
hsa00040 Pentose and glucuronate interconversions     8.446235e-07       28
hsa00860 Porphyrin and chlorophyll metabolism         3.474540e-06       38
hsa00500 Starch and sucrose metabolism                5.047958e-06       50
hsa00380 Tryptophan metabolism                        1.180799e-05       42
hsa00280 Valine, leucine and isoleucine degradation   2.437705e-05       44
hsa03320 PPAR signaling pathway                       4.831137e-05       70
hsa04976 Bile secretion                               5.608401e-05       70
hsa04975 Fat digestion and absorption                 8.538313e-05       44
hsa00120 Primary bile acid biosynthesis               1.087369e-04       16
hsa00591 Linoleic acid metabolism                     1.465698e-04       28</code></pre>
</div>
</div>
<p>What’s <em>down-regulated in liver</em> <em>compared to other tissues in the scope of our analysis</em>?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.data.frame</span>(<span class="fu">head</span>(keggres<span class="sc">$</span>greater, <span class="dv">30</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="st">"p.geomean"</span>, <span class="st">"stat.mean"</span>, <span class="st">"p.val"</span>, <span class="st">"set.size"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                            p.geomean stat.mean
hsa04260 Cardiac muscle contraction                      4.226923e-05 4.0485435
hsa04510 Focal adhesion                                  8.259292e-05 3.8042688
hsa04020 Calcium signaling pathway                       4.162904e-04 3.3711847
hsa04971 Gastric acid secretion                          4.992403e-04 3.3629267
hsa04540 Gap junction                                    2.260177e-03 2.8795191
hsa04512 ECM-receptor interaction                        1.063049e-02 2.3255222
hsa00512 Mucin type O-Glycan biosynthesis                1.216786e-02 2.3178456
hsa04310 Wnt signaling pathway                           1.365917e-02 2.2195968
hsa04010 MAPK signaling pathway                          1.744611e-02 2.1151954
hsa04740 Olfactory transduction                          1.772474e-02 2.1215169
hsa04144 Endocytosis                                     1.777223e-02 2.1102663
hsa04360 Axon guidance                                   2.267218e-02 2.0114316
hsa04810 Regulation of actin cytoskeleton                2.364352e-02 1.9896259
hsa04070 Phosphatidylinositol signaling system           4.524492e-02 1.7041613
hsa04742 Taste transduction                              4.633911e-02 1.7021996
hsa04666 Fc gamma R-mediated phagocytosis                5.200086e-02 1.6354382
hsa00603 Glycosphingolipid biosynthesis - globo series   5.488970e-02 1.6593014
hsa04916 Melanogenesis                                   6.589814e-02 1.5133803
hsa04960 Aldosterone-regulated sodium reabsorption       7.526569e-02 1.4512416
hsa04970 Salivary secretion                              7.787444e-02 1.4259650
hsa04966 Collecting duct acid secretion                  9.503669e-02 1.3287755
hsa04720 Long-term potentiation                          1.029612e-01 1.2717035
hsa04722 Neurotrophin signaling pathway                  1.100257e-01 1.2305044
hsa04012 ErbB signaling pathway                          1.306016e-01 1.1275055
hsa00604 Glycosphingolipid biosynthesis - ganglio series 1.335755e-01 1.1341217
hsa04730 Long-term depression                            1.385772e-01 1.0911743
hsa04330 Notch signaling pathway                         1.424131e-01 1.0774613
hsa04962 Vasopressin-regulated water reabsorption        1.465997e-01 1.0579484
hsa03010 Ribosome                                        1.579659e-01 1.0084071
hsa00562 Inositol phosphate metabolism                   1.619384e-01 0.9910218
                                                                p.val set.size
hsa04260 Cardiac muscle contraction                      4.226923e-05       76
hsa04510 Focal adhesion                                  8.259292e-05      200
hsa04020 Calcium signaling pathway                       4.162904e-04      176
hsa04971 Gastric acid secretion                          4.992403e-04       73
hsa04540 Gap junction                                    2.260177e-03       88
hsa04512 ECM-receptor interaction                        1.063049e-02       84
hsa00512 Mucin type O-Glycan biosynthesis                1.216786e-02       30
hsa04310 Wnt signaling pathway                           1.365917e-02      148
hsa04010 MAPK signaling pathway                          1.744611e-02      262
hsa04740 Olfactory transduction                          1.772474e-02       97
hsa04144 Endocytosis                                     1.777223e-02      201
hsa04360 Axon guidance                                   2.267218e-02      129
hsa04810 Regulation of actin cytoskeleton                2.364352e-02      209
hsa04070 Phosphatidylinositol signaling system           4.524492e-02       78
hsa04742 Taste transduction                              4.633911e-02       43
hsa04666 Fc gamma R-mediated phagocytosis                5.200086e-02       93
hsa00603 Glycosphingolipid biosynthesis - globo series   5.488970e-02       14
hsa04916 Melanogenesis                                   6.589814e-02       99
hsa04960 Aldosterone-regulated sodium reabsorption       7.526569e-02       42
hsa04970 Salivary secretion                              7.787444e-02       85
hsa04966 Collecting duct acid secretion                  9.503669e-02       27
hsa04720 Long-term potentiation                          1.029612e-01       69
hsa04722 Neurotrophin signaling pathway                  1.100257e-01      127
hsa04012 ErbB signaling pathway                          1.306016e-01       87
hsa00604 Glycosphingolipid biosynthesis - ganglio series 1.335755e-01       15
hsa04730 Long-term depression                            1.385772e-01       68
hsa04330 Notch signaling pathway                         1.424131e-01       47
hsa04962 Vasopressin-regulated water reabsorption        1.465997e-01       43
hsa03010 Ribosome                                        1.579659e-01       87
hsa00562 Inositol phosphate metabolism                   1.619384e-01       57</code></pre>
</div>
</div>
<p>Note that the p-values for pathways down-regulated in the liver are less significant than those of pathways up-regulated, likely due to by high dispersion among the comparison tissues.</p>
</section>
<section id="pathway-plots" class="level3">
<h3 class="anchored" data-anchor-id="pathway-plots">Pathway plots</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>keggrespathways <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">id =</span> <span class="fu">rownames</span>(keggres<span class="sc">$</span>less), keggres<span class="sc">$</span>less) <span class="sc">%&gt;%</span> </span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">5</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>  .<span class="sc">$</span>id <span class="sc">%&gt;%</span> </span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.character</span>() <span class="sc">%&gt;%</span></span>
<span id="cb91-6"><a href="#cb91-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># top 5, plus some pet pathways part of my starting hypothesis</span></span>
<span id="cb91-7"><a href="#cb91-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">append</span>(<span class="st">"hsa04976 Bile secretion"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb91-8"><a href="#cb91-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">append</span>(<span class="st">"hsa00860 Porphyrin and chlorophyll metabolism"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb91-9"><a href="#cb91-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">append</span>(<span class="st">"hsa00280 Valine, leucine and isoleucine degradation"</span>)</span>
<span id="cb91-10"><a href="#cb91-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-11"><a href="#cb91-11" aria-hidden="true" tabindex="-1"></a>keggresids <span class="ot">=</span> <span class="fu">str_sub</span>(keggrespathways, <span class="at">start =</span> <span class="dv">1</span>, <span class="at">end =</span> <span class="dv">8</span>)</span>
<span id="cb91-12"><a href="#cb91-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-13"><a href="#cb91-13" aria-hidden="true" tabindex="-1"></a>keggrespathways</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "hsa00830 Retinol metabolism"                          
[2] "hsa00982 Drug metabolism - cytochrome P450"           
[3] "hsa00980 Metabolism of xenobiotics by cytochrome P450"
[4] "hsa00140 Steroid hormone biosynthesis"                
[5] "hsa00983 Drug metabolism - other enzymes"             
[6] "hsa04976 Bile secretion"                              
[7] "hsa00860 Porphyrin and chlorophyll metabolism"        
[8] "hsa00280 Valine, leucine and isoleucine degradation"  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define plotting function for applying later</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>plot_pathway <span class="ot">&lt;-</span> <span class="cf">function</span>(pid) {<span class="fu">pathview</span>(<span class="at">gene.data =</span> foldchanges,</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">pathway.id =</span> pid, <span class="at">species =</span> <span class="st">"hsa"</span>, <span class="at">new.signature =</span> <span class="cn">FALSE</span>)}</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a><span class="co"># plot multiple pathways (plots saved to disk and returns a throwaway list object)</span></span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">=</span> <span class="fu">sapply</span>(keggresids, plot_pathway)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Typically, expression heat maps use the color-blind-unfriendly and unintuitive red for up-regulated expression, and green for decreased expression.</p>
<p>However, here, because I never inverted (multiplied by -1) the log2-fold-change values, green is for increased relative expression, and red is for decreased relative expression.</p>
<section id="hsa00830-retinol-metabolism" class="level4">
<h4 class="anchored" data-anchor-id="hsa00830-retinol-metabolism">hsa00830 Retinol metabolism</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hsa00830.pathview.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">hsa00830 Retinol metabolism</figcaption>
</figure>
</div>
</section>
<section id="hsa00982-drug-metabolism---cytochrome-p450" class="level4">
<h4 class="anchored" data-anchor-id="hsa00982-drug-metabolism---cytochrome-p450">hsa00982 Drug metabolism - cytochrome P450</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hsa00982.pathview.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">hsa00982 Drug metabolism - cytochrome P450</figcaption>
</figure>
</div>
</section>
<section id="hsa00980-metabolism-of-xenobiotics-by-cytochrome-p450" class="level4">
<h4 class="anchored" data-anchor-id="hsa00980-metabolism-of-xenobiotics-by-cytochrome-p450">hsa00980 Metabolism of xenobiotics by cytochrome P450</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hsa00980.pathview.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">hsa00980 Metabolism of xenobiotics by cytochrome P450</figcaption>
</figure>
</div>
</section>
<section id="hsa00983-drug-metabolism---other-enzymes" class="level4">
<h4 class="anchored" data-anchor-id="hsa00983-drug-metabolism---other-enzymes">hsa00983 Drug metabolism - other enzymes</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hsa00983.pathview.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">hsa00983 Drug metabolism - other enzymes</figcaption>
</figure>
</div>
</section>
<section id="hsa00140-steroid-hormone-biosynthesis" class="level4">
<h4 class="anchored" data-anchor-id="hsa00140-steroid-hormone-biosynthesis">hsa00140 Steroid hormone biosynthesis</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hsa00140.pathview.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">hsa00140 Steroid hormone biosynthesis</figcaption>
</figure>
</div>
</section>
<section id="hsa00983-drug-metabolism---other-enzymes-1" class="level4">
<h4 class="anchored" data-anchor-id="hsa00983-drug-metabolism---other-enzymes-1">hsa00983 Drug metabolism - other enzymes</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hsa00983.pathview.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">hsa00983 Drug metabolism - other enzymes</figcaption>
</figure>
</div>
</section>
<section id="hsa04976-bile-secretion" class="level4">
<h4 class="anchored" data-anchor-id="hsa04976-bile-secretion">hsa04976 Bile secretion</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hsa04976.pathview.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">hsa04976 Bile secretion</figcaption>
</figure>
</div>
<p>The bile secretion graphic is particularly interesting because it depicts spatial regulation across cell types, and those expectations (hypotheses) are upheld by the bulk RNA-seq data from GTEx. Most hepatocyte genes are up-regulated, whereas most cholangiocyte (epithelial cells of the bile duct) genes are not up-regulated.</p>
</section>
<section id="hsa00860-porphyrin-and-chlorophyll-metabolism" class="level4">
<h4 class="anchored" data-anchor-id="hsa00860-porphyrin-and-chlorophyll-metabolism">hsa00860 Porphyrin and chlorophyll metabolism</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hsa00860.pathview.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">hsa00860 Porphyrin and chlorophyll metabolism</figcaption>
</figure>
</div>
<p>Porphyrin metabolism is a curious case: not many of the GO term’s genes are up-regulated, and even along a linear pathway, not all the genes in are up-regulated. I am especially surprised to see biliverdin to bilirubin conversion down-regulated relative to the other tissues in this set. Meanwhile, two of bilirubin’s downstream steps are up-regulated.</p>
</section>
</section>
</section>
</section>
<section id="transcription-factor-enrichment-analysis" class="level1">
<h1>Transcription Factor Enrichment Analysis</h1>
<p>With <code>TFEA_ChIP</code>, we will leverage the contingency matrices crossing DEseq2 up v. down and previously-existing ChIP-seq (up v. down) data sets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>TFEA_DE_results_ordered <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(dplyr<span class="sc">::</span><span class="fu">select</span>(tissue_DE_results_wide,</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>                                                       <span class="st">"Genes"</span> <span class="ot">=</span> short_ensg, <span class="co">#symbol,</span></span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>                                                       <span class="st">"log2FoldChange"</span> <span class="ot">=</span> mean_log2FoldChange,</span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>                                                       <span class="st">"pvalue"</span> <span class="ot">=</span> mean_pvalue,</span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a>                                                       <span class="st">"padj"</span> <span class="ot">=</span> mean_padj))</span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a>TFEA_DE_results_ordered<span class="sc">$</span>log2FoldChange <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">1</span> <span class="sc">*</span> TFEA_DE_results_ordered<span class="sc">$</span>log2FoldChange</span>
<span id="cb94-8"><a href="#cb94-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-9"><a href="#cb94-9" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(TFEA_DE_results_ordered) <span class="ot">&lt;-</span> TFEA_DE_results_ordered<span class="sc">$</span>short_ensg</span>
<span id="cb94-10"><a href="#cb94-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-11"><a href="#cb94-11" aria-hidden="true" tabindex="-1"></a>TFEA_table <span class="ot">&lt;-</span> TFEA.ChIP<span class="sc">::</span><span class="fu">preprocessInputData</span>(TFEA_DE_results_ordered)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Some genes returned 1:many mapping to ENTREZ ID. Genes were assigned the first ENTREZ ID match found.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co">#extract vector with names of up-regulated genes</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>genes_upreg <span class="ot">&lt;-</span> TFEA.ChIP<span class="sc">::</span><span class="fu">Select_genes</span>(TFEA_table, <span class="at">min_LFC =</span> <span class="dv">4</span>)</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a><span class="co">#extract vector with names of non-responsive genes</span></span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a><span class="co">#genes_ctrl &lt;- TFEA.ChIP::Select_genes(TFEA_table,</span></span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a><span class="co">#    min_pval = 0.05, max_pval = 1, max_LFC = -4)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>DE_CM <span class="ot">&lt;-</span> <span class="fu">contingency_matrix</span>(genes_upreg) <span class="co"># generates list of contingency tables, one per dataset</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>pval_up_genes <span class="ot">&lt;-</span> <span class="fu">getCMstats</span>(DE_CM) <span class="co"># generates list of p-values and OR from association test</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="chip-transcription-factor-data" class="level2">
<h2 class="anchored" data-anchor-id="chip-transcription-factor-data">ChIP Transcription Factor data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>chip_index <span class="ot">&lt;-</span> <span class="fu">get_chip_index</span>(<span class="at">encodeFilter =</span> <span class="cn">TRUE</span>)</span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>DE_CM_chip <span class="ot">&lt;-</span> <span class="fu">contingency_matrix</span>(genes_upreg, <span class="co">#genes_ctrl,</span></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">chip_index =</span> chip_index)</span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a>DE_CM_chip_stats <span class="ot">&lt;-</span> <span class="fu">getCMstats</span>(DE_CM_chip, chip_index)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>TF_ranking <span class="ot">&lt;-</span> <span class="fu">rankTFs</span>(DE_CM_chip_stats, <span class="at">rankMethod =</span> <span class="st">"gsea"</span>, <span class="at">makePlot =</span> <span class="cn">FALSE</span>)</span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>TF_ranking <span class="sc">%&gt;%</span></span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"is_significant"</span> <span class="ot">=</span> <span class="fu">if_else</span>(pVal <span class="sc">&lt;=</span> <span class="fl">0.05</span>, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(is_significant), <span class="fu">desc</span>(ES), pVal) <span class="sc">%&gt;%</span></span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             TF       ES arg.ES pVal numberOfChIPs is_significant
FOXA2     FOXA2  0.99125      8 0.00             2           TRUE
HNF1A     HNF1A  0.97817     16 0.01             1           TRUE
HNF4G     HNF4G  0.97522     19 0.01             2           TRUE
NR2F6     NR2F6  0.97234     20 0.03             1           TRUE
HNF4A     HNF4A  0.96642     26 0.00             3           TRUE
FOXA1     FOXA1  0.94599     40 0.01             3           TRUE
NR2F2     NR2F2  0.94015     44 0.00             3           TRUE
ATF3       ATF3  0.76196     11 0.02             6           TRUE
GABPA     GABPA -0.69893    593 0.04             9           TRUE
CREB1     CREB1 -0.80579    628 0.03             5           TRUE
SIN3A     SIN3A -0.81379    654 0.05             5           TRUE
CHD2       CHD2 -0.86508    618 0.00             5           TRUE
TBP         TBP -0.87588    608 0.01             4           TRUE
MAZ         MAZ -0.88623    639 0.05             3           TRUE
ELF1       ELF1 -0.90544    627 0.00             5           TRUE
CBFB       CBFB -0.95049    660 0.03             2           TRUE
SMAD5     SMAD5 -0.99854    686 0.00             1           TRUE
NR5A1     NR5A1  0.95779     30 0.08             1          FALSE
HHEX       HHEX  0.95488     32 0.11             1          FALSE
GFI1       GFI1  0.95342     33 0.07             1          FALSE
ONECUT1 ONECUT1  0.94905     36 0.09             1          FALSE
MBD4       MBD4  0.94614     38 0.10             1          FALSE
SOX13     SOX13  0.94469     39 0.14             1          FALSE
PAXIP1   PAXIP1  0.93886     43 0.14             1          FALSE
FOXJ3     FOXJ3  0.93450     46 0.11             1          FALSE
FOXP1     FOXP1  0.93294     48 0.07             2          FALSE
ATF4       ATF4  0.92868     50 0.10             1          FALSE
ZNF609   ZNF609  0.92576     52 0.18             1          FALSE
THRB       THRB  0.92431     53 0.18             1          FALSE
MED1       MED1  0.91557     59 0.20             1          FALSE</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>TFrank_ES_p_plot <span class="ot">&lt;-</span> TF_ranking <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(ES)) <span class="sc">%&gt;%</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"rank"</span> <span class="ot">=</span> <span class="fu">row_number</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> ES, <span class="at">x =</span> rank, <span class="at">color =</span> pVal)) <span class="sc">+</span></span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>(<span class="at">option =</span> <span class="st">"D"</span>) <span class="sc">+</span></span>
<span id="cb101-6"><a href="#cb101-6" aria-hidden="true" tabindex="-1"></a>  gghighlight<span class="sc">::</span><span class="fu">gghighlight</span>(pVal <span class="sc">&lt;=</span> .<span class="dv">05</span>, <span class="co">#keep_scales = TRUE,</span></span>
<span id="cb101-7"><a href="#cb101-7" aria-hidden="true" tabindex="-1"></a>                           <span class="at">label_key =</span> TF,</span>
<span id="cb101-8"><a href="#cb101-8" aria-hidden="true" tabindex="-1"></a>                           <span class="at">unhighlighted_params =</span> <span class="fu">list</span>(<span class="at">color =</span> <span class="cn">NULL</span>, <span class="at">fill =</span> <span class="cn">NULL</span>,</span>
<span id="cb101-9"><a href="#cb101-9" aria-hidden="true" tabindex="-1"></a>                                                       <span class="at">size =</span> <span class="fl">0.3</span>, <span class="at">alpha =</span> .<span class="dv">5</span>)) <span class="sc">+</span></span>
<span id="cb101-10"><a href="#cb101-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb101-11"><a href="#cb101-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">1.25</span>, <span class="fl">1.25</span>)) <span class="sc">+</span></span>
<span id="cb101-12"><a href="#cb101-12" aria-hidden="true" tabindex="-1"></a>  <span class="co">#scale_x_continuous(trans = "log1p") +</span></span>
<span id="cb101-13"><a href="#cb101-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Enrichment score by rank, pVal highlighted"</span>,</span>
<span id="cb101-14"><a href="#cb101-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Enrighment score"</span>,</span>
<span id="cb101-15"><a href="#cb101-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Rank"</span>,</span>
<span id="cb101-16"><a href="#cb101-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Enrichment score of transcription factors by rank. p-values &lt; .05 are highlighted, other TFs are grey."</span>)</span>
<span id="cb101-17"><a href="#cb101-17" aria-hidden="true" tabindex="-1"></a>TFrank_ES_p_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="2024_01_03-GTEX_RNA_seq_liver_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Notes on TF_ranking results:</p>
<ul>
<li>HNF4 (Hepatocyte Nuclear Factor 4) is a nuclear receptor protein mostly expressed in the liver, gut, kidney, and pancreatic beta cells that is critical for liver development.</li>
<li>Forkhead box protein A2 (FOXA2), also known as hepatocyte nuclear factor 3-beta (HNF-3B), is a transcription factor that plays an important role during development</li>
<li>ATF-3 (Cyclic AMP-dependent transcription factor) is an activating member of the mammalian activation transcription factor/cAMP responsive element-binding (CREB) protein family. <em>ATF-3 is induced upon physiological stress in various tissues.</em></li>
<li>Forkhead box protein A1 (FOXA1), also known as hepatocyte nuclear factor 3-alpha (HNF-3A), is a transcriptional activator for liver-specific transcripts such as albumin and transthyretin, and they also interact with chromatin as a pioneer factor.</li>
<li>JUND: a functional component of the AP1 transcription factor complex. It has been proposed to protect cells from p53-dependent senescence and apoptosis.</li>
<li>TAF1 is TFIID subunit 1, a general pol II transcriptional complex component.</li>
<li>REST: RE1-silencing transcription factor gene encodes a transcriptional repressor which represses neuronal genes in non-neuronal tissues.</li>
<li>HNF1 homeobox A (hepatocyte nuclear factor 1 homeobox A), also known as HNF1A, is ubiquitously expressed in many tissues and cell types. The protein encoded by this gene is a transcription factor that is highly expressed in the liver and is involved in the regulation of the expression of several liver-specific genes.</li>
</ul>
<p>The GSEA option was unhelpful at sorting TFs by the level of evidence to support them (all enrichment scores were 1, and all p-values were 0). Wilcoxon doesn’t make a pretty plot, but it gives us helpful sorting data.</p>
<p>Still, I’m not impressed by these results. Even with more stringent filtering (log2-fold-change, p-value), I still can’t get a list that looks specific to the liver.</p>
<section id="run-gsea-on-tfea.chip" class="level3">
<h3 class="anchored" data-anchor-id="run-gsea-on-tfea.chip">Run GSEA on TFEA.ChIP</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>GSEA.result[[<span class="st">"Enrichment.table"</span>]] <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">arrange</span>(<span class="st">`</span><span class="at">pval.adj</span><span class="st">`</span>, <span class="fu">desc</span>(ES)) <span class="sc">%&gt;%</span> <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">40</span>) <span class="sc">%&gt;%</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">!</span><span class="fu">c</span>(<span class="st">"pval.adj"</span>, <span class="st">"Arg.ES"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    Accession   Cell Treatment      TF      ES p.val
1     ENCSR297GII.HNF4G.liver  liver             HNF4G 0.54053     0
2      ENCSR016BMM.TAF1.liver  liver              TAF1 0.49766     0
3     ENCSR735KEY.FOXA1.liver  liver             FOXA1 0.49263     0
4   ENCSR000EZP.SREBF1.Hep-G2 Hep-G2            SREBF1 0.48636     0
5     ENCSR310NYI.FOXA2.liver  liver             FOXA2 0.48343     0
6     ENCSR324RCI.FOXA1.liver  liver             FOXA1 0.48302     0
7     ENCSR000BQW.MBD4.Hep-G2 Hep-G2              MBD4 0.47427     0
8      ENCSR205FOW.ATF3.liver  liver              ATF3 0.47074     0
9      ENCSR480LIS.ATF3.liver  liver              ATF3 0.47024     0
10  ENCSR000EVQ.TCF7L2.Hep-G2 Hep-G2            TCF7L2 0.46749     0
11  ENCSR000EZO.SREBF2.Hep-G2 Hep-G2            SREBF2 0.45675     0
12   ENCSR516HUP.ZBTB33.liver  liver            ZBTB33 0.45420     0
13     ENCSR893QWP.REST.liver  liver              REST 0.45235     0
14    ENCSR080XEY.FOXA2.liver  liver             FOXA2 0.44996     0
15     ENCSR736BUG.EGR1.liver  liver              EGR1 0.44549     0
16    ENCSR656JZL.HHEX.Hep-G2 Hep-G2              HHEX 0.44122     0
17   ENCSR800QIT.HNF1A.Hep-G2 Hep-G2             HNF1A 0.43966     0
18     ENCSR867WPH.REST.liver  liver              REST 0.43082     0
19    ENCSR669LCD.ATF4.Hep-G2 Hep-G2              ATF4 0.42999     0
20    ENCSR000BQX.NFIC.Hep-G2 Hep-G2              NFIC 0.42440     0
21     ENCSR837GTK.JUND.liver  liver              JUND 0.42418     0
22     ENCSR196HGZ.JUND.liver  liver              JUND 0.42393     0
23      ENCSR521IID.MAX.liver  liver               MAX 0.41846     0
24   ENCSR267DFA.FOXA1.Hep-G2 Hep-G2             FOXA1 0.41741     0
25 ENCSR887LYD.SMARCC2.Hep-G2 Hep-G2           SMARCC2 0.41697     0
26     ENCSR290ZOS.EGR1.liver  liver              EGR1 0.40709     0
27   ENCSR620YNB.KAT2B.Hep-G2 Hep-G2             KAT2B 0.40506     0
28   ENCSR000BRO.MYBL2.Hep-G2 Hep-G2             MYBL2 0.40453     0
29   ENCSR345YWJ.ZBTB33.liver  liver            ZBTB33 0.40031     0
30      ENCSR994YLZ.YY1.liver  liver               YY1 0.39534     0
31   ENCSR000BVM.NR2F2.Hep-G2 Hep-G2             NR2F2 0.39042     0
32    ENCSR444LIN.TCF7.Hep-G2 Hep-G2              TCF7 0.38687     0
33    ENCSR849FVL.GFI1.Hep-G2 Hep-G2              GFI1 0.38592     0
34   ENCSR029LBT.FOXP1.Hep-G2 Hep-G2             FOXP1 0.38317     0
35   ENCSR000EEW.ESRRA.Hep-G2 Hep-G2             ESRRA 0.38049     0
36    ENCSR000BHU.RXRA.Hep-G2 Hep-G2              RXRA 0.37795     0
37   ENCSR000EEU.HNF4A.Hep-G2 Hep-G2             HNF4A 0.37548     0
38   ENCSR791AGT.ZNF24.Hep-G2 Hep-G2             ZNF24 0.37417     0
39   ENCSR413AJG.FOXJ3.Hep-G2 Hep-G2             FOXJ3 0.37378     0
40     ENCSR000BJX.SP1.Hep-G2 Hep-G2               SP1 0.37328     0</code></pre>
</div>
</div>
<p>The above table shows that GSEA (in addition to TFEA.ChIP) also returns many liver-implicated transcriptional regulators. The above table is sorted in descending order of effect size (running enrichment score), and also displays the accession ID of the tissue sample that generated the ChIP seq data set. The TFs (transcription factors) can be in the table more than once.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>GSEA.result[[<span class="st">"Enrichment.table"</span>]] <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">count</span>(TF) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(n)) <span class="sc">%&gt;%</span> <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       TF  n
1    CTCF 31
2   EP300 11
3     MAX 11
4    JUND 10
5    REST 10
6   GABPA  9
7     MYC  7
8    TAF1  7
9  ZBTB33  7
10   ATF3  6</code></pre>
</div>
</div>
<p>The above table counts the number of line items for each TF; despite CTCF (a practically ubiquitous transcriptional and chromatin regulator) being so highly represented across data sets, its running effect size was not high enough to make it show up in the top 40 (5.8%) of line items. (Same goes for EP300.)</p>
<p>What this result shows is that the number of ChIP datasets under consideration in this package is not evenly distributed across all potential transcription factors, and so the number of times a transcription factor is identified as a hit is not a good measure of significance or salience.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://utteranc.es/client.js" repo="pdcherry/blogComments" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Copyright 2023, Patrick Cherry <a rel="me" href="https://genomic.social/@pcherry"><span class="citation" data-cites="pcherry">@pcherry</span><span class="citation" data-cites="genomic.social">@genomic.social</span></a></div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>