{
  "hash": "6952b3dbb2ce868ea3103f4bd010d50b",
  "result": {
    "markdown": "---\ntitle: \"A non-linearity-assuming correlation coefficient: XICOR\"\nauthor: \"Patrick Cherry\"\ndate: \"2023/12/30\"\ncategories:\n  - code\n  - statistics\nimage: \"\"\nexecute:\n  freeze: true\n---\n\n## Introduction and motivaation\n\n\n## Load library\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(XICOR)\nlibrary(psych)\ntheme_set(theme_dark())\n```\n:::\n\n\n## Load data\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"pressure\")\npenguins <- palmerpenguins::penguins_raw\ndata(\"peas\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in data(\"peas\"): data set 'peas' not found\n```\n:::\n:::\n\n\n### Vapor Pressure of mercury\nData on the relation between temperature in degrees Celsius and vapor pressure of mercury in millimeters (of mercury).\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(pressure)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 19\nColumns: 2\n$ temperature <dbl> 0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240,…\n$ pressure    <dbl> 0.0002, 0.0012, 0.0060, 0.0300, 0.0900, 0.2700, 0.7500, 1.…\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npressure_point_plot <- pressure %>%\n  ggplot(aes(y = pressure, x = temperature)) +\n  geom_point() +\n  stat_smooth(method = \"lm\", formula = \"y ~ x\", color = \"orange\") +\n  stat_smooth(method = \"glm\", formula = \"y ~ x + I(x^5)\", color = \"blue\") +\n  # stat_smooth(method = \"glm\", formula = \"y ~ x + exp(x)\", color = \"green\",\n  #             method.args = list(\"family\" = \"inverse.gaussian\")) +\n  labs(title = \"Plot of non-linar data, vapor pressure of mercury vs. temperature\",\n       subtitle = \"Vapor pressure is know a priori as a non-linear function of temperature.\",\n       caption = \"Linear regression in orange, x^5 glm in blue.\")\npressure_point_plot\n```\n\n::: {.cell-output-display}\n![](2023_12_30-a_non_linearity_assuming_correlation_calculation_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nLet's compare the model fit outputs from these two.\n\n::: {.cell}\n\n```{.r .cell-code}\npressure_lm <- lm(formula = \"pressure ~ temperature\", data = pressure)\npressure_glm <- glm(formula = \"pressure ~ I(temperature^5)\", data = pressure)\n```\n:::\n\n\n#### linear model summary\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(pressure_lm); summary(pressure_lm)[[\"r.squared\"]]^0.5\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = \"pressure ~ temperature\", data = pressure)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-158.08 -117.06  -32.84   72.30  409.43 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -147.8989    66.5529  -2.222 0.040124 *  \ntemperature    1.5124     0.3158   4.788 0.000171 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 150.8 on 17 degrees of freedom\nMultiple R-squared:  0.5742,\tAdjusted R-squared:  0.5492 \nF-statistic: 22.93 on 1 and 17 DF,  p-value: 0.000171\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7577923\n```\n:::\n:::\n\n\n#### glm (quintic) model summary\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(pressure_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = \"pressure ~ I(temperature^5)\", data = pressure)\n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      -1.756e+01  7.482e+00  -2.347   0.0313 *  \nI(temperature^5)  1.266e-10  3.651e-12  34.663   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for gaussian family taken to be 745.31)\n\n    Null deviance: 908195  on 18  degrees of freedom\nResidual deviance:  12670  on 17  degrees of freedom\nAIC: 183.47\n\nNumber of Fisher Scoring iterations: 2\n```\n:::\n:::\n\n\nWe can see that the linear summary shows the linear fit is poor: the standard error is high relative to the estimate. Another metric that statistical model practitioners will note is the R-squared, or the correlation coefficient, is low (for data from the physical science): `R^2 = 0.574`. If we square root the R^2, we get a correlation coefficient of `R = 0.758`. But we can see visually from the plot that the data do follow a clear trend.\n\nMeanwhile, the generalized linear model with a `pressure^5` term shows a very low error compared to the estimate. (The error is 34.7 times lower than the estimate.) However, this model summary output lacks a correlation coefficient. __Even though we can get many measures of the fit of a model, if we use anything other than a simple linear model, a correlation coefficient doesn't exist.__ At least a correlation coefficient we are used to: a Pearson r. This is a fact of statistics, and is a consequence of the assumption of Pearson r that the data are linearly related.\n\n### XICOR correlation coefficient\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxicor(pressure$pressure, pressure$temperature)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.85\n```\n:::\n:::\n\n\nAh, but if \n\n### Palmer Penguins data\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 344\nColumns: 17\n$ studyName             <chr> \"PAL0708\", \"PAL0708\", \"PAL0708\", \"PAL0708\", \"PAL…\n$ `Sample Number`       <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 1…\n$ Species               <chr> \"Adelie Penguin (Pygoscelis adeliae)\", \"Adelie P…\n$ Region                <chr> \"Anvers\", \"Anvers\", \"Anvers\", \"Anvers\", \"Anvers\"…\n$ Island                <chr> \"Torgersen\", \"Torgersen\", \"Torgersen\", \"Torgerse…\n$ Stage                 <chr> \"Adult, 1 Egg Stage\", \"Adult, 1 Egg Stage\", \"Adu…\n$ `Individual ID`       <chr> \"N1A1\", \"N1A2\", \"N2A1\", \"N2A2\", \"N3A1\", \"N3A2\", …\n$ `Clutch Completion`   <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"No\", …\n$ `Date Egg`            <date> 2007-11-11, 2007-11-11, 2007-11-16, 2007-11-16,…\n$ `Culmen Length (mm)`  <dbl> 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34…\n$ `Culmen Depth (mm)`   <dbl> 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18…\n$ `Flipper Length (mm)` <dbl> 181, 186, 195, NA, 193, 190, 181, 195, 193, 190,…\n$ `Body Mass (g)`       <dbl> 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 34…\n$ Sex                   <chr> \"MALE\", \"FEMALE\", \"FEMALE\", NA, \"FEMALE\", \"MALE\"…\n$ `Delta 15 N (o/oo)`   <dbl> NA, 8.94956, 8.36821, NA, 8.76651, 8.66496, 9.18…\n$ `Delta 13 C (o/oo)`   <dbl> NA, -24.69454, -25.33302, NA, -25.32426, -25.298…\n$ Comments              <chr> \"Not enough blood for isotopes.\", NA, NA, \"Adult…\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npenguin_point_plot <- penguins %>%\n  ggplot(aes(y = `Delta 13 C (o/oo)`, x = `Date Egg`)) +\n  geom_point() +\n  stat_smooth(method = \"lm\", formula = \"y ~ x\", color = \"orange\")\n  # stat_smooth(method = \"glm\", formula = \"y ~ x + exp(x)\", color = \"green\",\n  #             method.args = list(\"family\" = \"inverse.gaussian\")) +\n  # labs(title = \"Plot of non-linar data, vapor pressure of mercury vs. temperature\",\n  #      subtitle = \"Vapor pressure is know a priori as a non-linear function of temperature.\",\n  #      caption = \"Linear regression in orange, x^5 glm in blue.\")\npenguin_point_plot\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 13 rows containing non-finite values (`stat_smooth()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 13 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](2023_12_30-a_non_linearity_assuming_correlation_calculation_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "2023_12_30-a_non_linearity_assuming_correlation_calculation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}